### ISSUE TITLE
and how to i use this ?

### ISSUE THREAD

**Issue by cloudn1ne** [pcdangio/ros-calibration_imu#10]
I've added the correct message type to my IMU so it publishes the right topic - and the program compiles and runs, and what do i do then with the generated calibration data ? - is there a sample somewhere how the data gets used to correct the IMU readings. tia

**Comment by pcdangio** [comment]
the program generates a 4x4 calibration matrix, which is essentially just a homogeneous transformation matrix that translates/rotates/scales any newly measured point to apply the calibration. so all you need to do is take your 3x1 (x, y, z) measurement, turn it into a 4x1 vector (x, y, z, 1.0), and multiply it against the calibration matrix. The result will be a 4x1 vector that contains the calibrated data point (x, y, z, 1.0). All you need to do then is extract the x,y,z out of that 4x1 vector and that's your calibrated measurement. So if your calibration matrix is T, your uncalibrated data vector is u, and your calibrated data vector is c:

c = T * u

Do that for every single new measurement that your IMU takes. This applies both for the accelerometer calibration matrix as well as the magnetometer calibration matrix. Hopefully that helps!

**Comment by cloudn1ne** [comment]
thank you for the explanation - i split out the 3x3 part (deformation) and a 1x3 part (shift) and then apply it like below - probably not very mathematical, but seems to work ;)

`
void IMU_ApplyMagTransformation(double x, double y, double z, double *x_cal, double *y_cal, double *z_cal)
{

  double uncalibrated_values[3] = { x, y, z };
/*
  uncalibrated_values[0] = x;
  uncalibrated_values[1] = y;
  uncalibrated_values[2] = z;
*/
  double result[3] = {0, 0, 0};

  // apply transformation matrix (correct for sphere deformations)
  for (int i=0; i<3; ++i)
  {
    for (int j=0; j<3; ++j)
    {     
       result[i] += onboard_imu_mag_cal_matrix[i][j] * uncalibrated_values[j];
    }
  }

  // apply bias (shift sphere center)
  for (int i=0; i<3; ++i) 
  {
    result[i] = result[i] + onboard_imu_mag_bias[i];
  }
  
  *x_cal = result[0];      
  *y_cal = result[1];
  *z_cal = result[2];  
}`

**Comment by pcdangio** [comment]
You can apply it like that, but there is an easier (and more computationally efficient) way if you are using ROS or Eigen (Eigen comes with ROS):

```cpp
// Include the Eigen Dense library for matrix/vector operations.
#include <Eigen/Dense>

// Create your 4x4 calibration matrix somewhere else in your code to use it when a new measurement comes in.
// NOTE: a-p are your matrix coefficients generated from the calibration routine.
Eigen::Matrix4d C {{a, b, c, d}, {e, f, g, h}, {i, j, k, l}, {m, n, o, p}};

// Create a function for applying the calibration.
// Measurement components are passed in by reference so they can be updated with the calibrated values.
void apply_calibration(double& x, double& y, double& z)
{
    // First turn your measurement into a 4x1 vector, with the last element being 1.0:
    Eigen::Vector4d uncalibrated(x, y, z, 1.0);

    // Next, multiply the calibration matrix with the uncalibrated measurement.
    // This results in a new 4x1 vector, who's first 3 elements contain the calibrated points.
    Eigen::Vector4d calibrated = C * uncalibrated;

    // Now extract your calibrated measurements and put them back into the reference parameters for use after the function is called.
    x = calibrated.x();
    y = calibrated.y();
    z = calibrated.z();
}
```

**Comment by cloudn1ne** [comment]
thanks again - i will try that - my code runs on an STM32 so i need to check if the Eigen lib actually compiles there (no FPU ..)
