### ISSUE TITLE
How to use the calibrated data question?

### ISSUE THREAD

**Issue by vimalrobotics** [pcdangio/ros-calibration_imu#12]

**Comment by pcdangio** [comment]
The calibration gives you a 4x4 transformation matrix. All you have to do is take your x/y/z measurement, and put it into a 4x1 vector [x, y , z, 1], and then take the calibration matrix and multiply it by that vector. The result is the calibrated measurement, which will also be a 4x1 vector. Just extract the calibrated x/y/z values from the resulting 4x1 vector. Does that help?

**Comment by vimalrobotics** [comment]
Thank you paul

**Comment by vimalrobotics** [comment]
Would you please send me a reference link for this calibrating technique? It would be really appreciated.
