### ISSUE TITLE
Installing Qt 5+ Data Visualization Module (Qt module for 3D data visualization)

### ISSUE THREAD

**Issue by SahanGura** [pcdangio/ros-calibration_imu#6]
Can you please provide proper resources to install this dependency in Ubuntu 18.04?

**Comment by pcdangio** [comment]
This dependency can be installed using either the Qt installer (new installation) or Qt Maintenance Tool (existing installation). When you run these tools, they give you the ability to select which packages to install as part of Qt. ```Data Visualization``` is one of the packages that you can select to be included in your Qt installation. Let me know if that helps.

![image](https://user-images.githubusercontent.com/13617493/134342014-8fb600fa-e5c0-4420-9a32-1ec71b4fa2ef.png)
