### ISSUE TITLE
Standard ROS messages (sensor_msgs/MagneticField)

### ISSUE THREAD

**Issue by jcremona** [pcdangio/ros-calibration_imu#7]
Hi! I have been using this tool to calibrate my magnetometer and it has been very useful. However, I usually work with the standard ROS magnetometer messages (sensor_msgs/MagneticField). Therefore, I had to modify the code of this tool to be able to use it. Is there a reason why this tool uses its own messages (sensor_msgs_ext/magnetometer)? Thanks.

**Comment by pcdangio** [comment]
glad the tool has been useful for you! i originally wrote the tool for a custom project of mine, and then decided to open source it. haven't gotten around to making a branch for the standard sensor_msgs interface. if you have something you'd be willing to push to another branch in this repo i'd welcome it!

i use my own sensor_msgs_ext definitions in my projects for higher efficiency (and simplicity)

**Comment by avanmalleghem** [comment]
The following fork deals and solves this issue : https://github.com/Botronics-be/ros-calibration_imu
